export const fakePopularTVShowList = [
  {
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [18, 80, 10766],
    id: 209265,
    name: "Terra e Paixão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview: "",
    popularity: 2973.431,
    poster_path: "/voaKRrYExZNkf1E4FZExU7fTd8w.jpg",
    vote_average: 6.6,
    vote_count: 5,
  },
  {
    backdrop_path: "/8qlKzvR68dH0ZaJFG9XBEctvvUo.jpg",
    first_air_date: "2011-02-12",
    genre_ids: [35],
    id: 63935,
    name: "Les Mystères de l'amour",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Les Mystères de l'amour",
    overview:
      "Les Mystères de l'amour is a French television series originally broadcast by TMC. It was created by Jean-Luc Azoulay. The original French title literally translates to The Mysteries of Love",
    popularity: 1673.551,
    poster_path: "/mtUhIHbhw0GCacVnPam8p4vwejB.jpg",
    vote_average: 5.9,
    vote_count: 8,
  },

  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2627.101,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 4.5,
    vote_count: 25,
  },
  {
    backdrop_path: null,
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215315,
    name: "Rabb Se Hai Dua",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "रब्ब से है दुआ",
    overview:
      "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
    popularity: 2517.28,
    poster_path: "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
    vote_average: 4.5,
    vote_count: 4,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "Teri Meri Doriyaan",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "तेरी मेरी डोरियाँ",
    overview:
      "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
    popularity: 2489.235,
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 4.9,
    vote_count: 9,
  },
  {
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [18, 80, 10766],
    id: 209265,
    name: "Terra e Paixão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview: "",
    popularity: 2829.656,
    poster_path: "/voaKRrYExZNkf1E4FZExU7fTd8w.jpg",
    vote_average: 4.3,
    vote_count: 3,
  },
  {
    backdrop_path: "/jWYzdSv85nncRxfDwYSQKKlnuhG.jpg",
    first_air_date: "2023-03-09",
    genre_ids: [18],
    id: 221949,
    name: "Chashni",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "चाशनी",
    overview:
      "An untoward incident mars the loving relationship between two sisters- Chandni and Roshni. Years later, fate brings them face to face only to find out that they are daughter-in-law and mother-in-law for each other. Thus, begins a typical saas-bahu saga.",
    popularity: 2114.41,
    poster_path: "/qz3mN7SCTVskkDIBwceV4FXv2VC.jpg",
    vote_average: 4.4,
    vote_count: 4,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    popularity: 1489.768,
    poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
    vote_average: 4.9,
    vote_count: 38,
  },
  {
    backdrop_path: "/1Ezn8u1iEOwLHySpwnafinVWeXG.jpg",
    first_air_date: "2023-05-14",
    genre_ids: [18],
    id: 226002,
    name: "Gen Z",
    origin_country: ["CN"],
    original_language: "zh",
    original_name: "後浪",
    overview: "",
    popularity: 1970.8,
    poster_path: "/hquRJB69g1VnRzwX1yWWT7Cz9D6.jpg",
    vote_average: 9,
    vote_count: 1,
  },
  {
    backdrop_path: "/lcSvkJ2Rob3ICIOCUJahw3kgSYZ.jpg",
    first_air_date: "2023-03-14",
    genre_ids: [18],
    id: 216390,
    name: "Woman in a Veil",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "비밀의 여자",
    overview:
      "Jung Gyul Wool loses her vision and ability to walk because of her materialistic husband and his mistress. Despite her shortcomings, she hatches a plot to seek revenge.",
    popularity: 1520.298,
    poster_path: "/5ERr09UrnVm0hdXBeefNVtQMxI.jpg",
    vote_average: 4.7,
    vote_count: 6,
  },
  {
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    first_air_date: "2023-01-23",
    genre_ids: [9648, 18],
    id: 202250,
    name: "Dirty Linen",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Dirty Linen",
    overview:
      "To exact vengeance, a young woman infiltrates the household of an influential family as a housemaid to expose their dirty secrets. However, love will get in the way of her revenge plot.",
    popularity: 1985.899,
    poster_path: "/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg",
    vote_average: 5.1,
    vote_count: 18,
  },
  {
    backdrop_path: "/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg",
    first_air_date: "2023-02-13",
    genre_ids: [10759, 35, 18],
    id: 215803,
    name: "Batang Quiapo",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Batang Quiapo",
    overview:
      "A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.",
    popularity: 1482.746,
    poster_path: "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
    vote_average: 5.5,
    vote_count: 16,
  },
  {
    backdrop_path: null,
    first_air_date: "2005-09-05",
    genre_ids: [18, 35],
    id: 36361,
    name: "Ulice",
    origin_country: ["CZ"],
    original_language: "cs",
    original_name: "Ulice",
    overview:
      "Ulice is a Czech soap opera produced and broadcast by Nova. In the Czech language Ulice means street.\n\nThe show describes the lives of the Farský, Jordán, Boháč, Nikl, and Liška families and many other people that live in Prague. Their daily battle against real problems of living in a modern world like divorce, love, betrayal and illness or disease. Ulice often shows crime.",
    popularity: 1987.544,
    poster_path: "/3ayWL13P1HeRnyVL9lU9flOdZjq.jpg",
    vote_average: 2.8,
    vote_count: 12,
  },
  {
    backdrop_path: "/xYiI6QEZvx8Z4La1oHvApyZHpOU.jpg",
    first_air_date: "2023-01-16",
    genre_ids: [10766, 35],
    id: 209117,
    name: "Never Give Up",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Vai na Fé",
    overview:
      "Sol is a hardworking woman who has the chance to work as a backing vocalist for a funk singer and return to dancing, as she did in her youth. Torn between family pressure and passion for the stage, she must face the judgment of her church's members and conflicts with her family. The new chance will make her reconnect with her past in many ways, leading her to find her great youth love.",
    popularity: 1921.694,
    poster_path: "/6QNohzb7YUJ6eWZkXAYU8KGIq.jpg",
    vote_average: 7.9,
    vote_count: 10,
  },
  {
    backdrop_path: "/4NcAz1QIqYnhe3u2pnVEVNwfTZf.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "Ghum Hai Kisi Ke Pyaar Mein",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "घुम है किसिकी प्यार में",
    overview:
      "Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?",
    popularity: 1930.943,
    poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
    vote_average: 5.6,
    vote_count: 39,
  },
  {
    backdrop_path: "/mUZqXvIWtyEQ8YrfCiRVqfNYaMl.jpg",
    first_air_date: "2023-05-18",
    genre_ids: [35, 18],
    id: 195670,
    name: "XO, Kitty",
    origin_country: ["US"],
    original_language: "en",
    original_name: "XO, Kitty",
    overview:
      "Teen matchmaker Kitty Song Covey thinks she knows everything there is to know about love. But when she moves halfway across the world to reunite with her long-distance boyfriend, she’ll soon realize that relationships are a lot more complicated when it’s your own heart on the line.",
    popularity: 1053.871,
    poster_path: "/hxvTdKAwv27PUfpXOQp6AwWr6V.jpg",
    vote_average: 8.5,
    vote_count: 127,
  },
  {
    backdrop_path: "/gNPWlhUXhyWiHv9qxr57tvT0WwS.jpg",
    first_air_date: "2014-10-07",
    genre_ids: [18, 10765],
    id: 60735,
    name: "The Flash",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Flash",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    popularity: 1184.637,
    poster_path: "/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg",
    vote_average: 7.8,
    vote_count: 10433,
  },
  {
    backdrop_path: "/i8NGdMIyZnGNpSHLDtpPwYXidPe.jpg",
    first_air_date: "2020-11-16",
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: "Imlie",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "इमली",
    overview:
      "All Imlie wanted was to create a name for herself in the city. But upon her arrival, she finds herself caught in the middle of Aditya and Malini's love story.",
    popularity: 1744.722,
    poster_path: "/sltUDXvpDZK3aVIdtkbImhcJv8t.jpg",
    vote_average: 4.6,
    vote_count: 12,
  },
  {
    backdrop_path: "/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg",
    first_air_date: "2011-01-10",
    genre_ids: [10763, 10767],
    id: 101463,
    name: "Al rojo vivo",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Al rojo vivo",
    overview: "",
    popularity: 1628.887,
    poster_path: "/ag6PmoBxkF2s1uY3An618NCEt3g.jpg",
    vote_average: 3.1,
    vote_count: 11,
  },
  {
    backdrop_path: "/zrv9dK9FQepCS2KCNJ04LYsjsDd.jpg",
    first_air_date: "2023-04-02",
    genre_ids: [10764],
    id: 210479,
    name: "Survivor Québec",
    origin_country: ["CA"],
    original_language: "fr",
    original_name: "Survivor Québec",
    overview: "",
    popularity: 1624.015,
    poster_path: "/cuVZay78P1WkBet12KF8tRJYtp4.jpg",
    vote_average: 8,
    vote_count: 1,
  },
  {
    backdrop_path: "/tio0dduiKFPjOEAf9iPLb9v9MNZ.jpg",
    first_air_date: "2022-11-14",
    genre_ids: [10759, 18],
    id: 211128,
    name: "The Iron Heart",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "The Iron Heart",
    overview:
      "An undercover agent goes on a dangerous mission to bring down a crime ring. Fueled by a bitter and painful past, he along with his allies faces the grueling task that will challenge his resolve and strength.",
    popularity: 1102.972,
    poster_path: "/91V6NI1JXCTDhaSSkoY7T87hk09.jpg",
    vote_average: 6.5,
    vote_count: 6,
  },
  {
    backdrop_path: "/peqIR6V2zZdzp3MEZBCwtqw1Bf2.jpg",
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215426,
    name: "Pyaar Ke Saat Vachan - Dharam Patni",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Pyaar Ke Saat Vachan - Dharam Patni",
    overview:
      "What will happen when Ravi Randhawa, a business tycoon, meets Pratiksha Parekh, a simple school teacher? Will sparks fly? Or is there no happy-ever-after for the opposite personalities?",
    popularity: 1507.411,
    poster_path: "/fMR23wg4yNsTEhqyYIfvzDAOEae.jpg",
    vote_average: 6,
    vote_count: 2,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/8tv3QAZrR94nfLkhsezPcc3bza5.jpg",
    id: 76954,
    name: "The Mechanism",
    original_language: "pt",
    original_name: "O Mecanismo",
    overview:
      "A scandal erupts in Brazil during an investigation of alleged government corruption via oil and construction companies. Loosely inspired by true events.",
    poster_path: "/tVnmpjhELgmh7so237wgDUck7kO.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 14.69,
    first_air_date: "2018-03-23",
    vote_average: 7.125,
    vote_count: 108,
    origin_country: ["BR"],
  },
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 216.531,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 11739,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/sccDflItNho4OiHkzpiDxB2fUFw.jpg",
    id: 1418,
    name: "The Big Bang Theory",
    original_language: "en",
    original_name: "The Big Bang Theory",
    overview:
      "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 74.282,
    first_air_date: "2007-09-24",
    vote_average: 7.879,
    vote_count: 10002,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r7zUXadc1saFFSWz8lbUx7q9bkG.jpg",
    id: 1402,
    name: "The Walking Dead",
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 248.834,
    first_air_date: "2010-10-31",
    vote_average: 8.116,
    vote_count: 14984,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg",
    id: 77169,
    name: "Cobra Kai",
    original_language: "en",
    original_name: "Cobra Kai",
    overview:
      "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
    poster_path: "/m7tG5E1EbywuwTsl6hq990So0Bx.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 35],
    popularity: 101.484,
    first_air_date: "2018-05-02",
    vote_average: 8.211,
    vote_count: 5602,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 315.24,
    first_air_date: "2011-04-17",
    vote_average: 8.435,
    vote_count: 21195,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 212.071,
    first_air_date: "2016-07-15",
    vote_average: 8.631,
    vote_count: 15594,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/p7PLOCD4bqLV4sJmeLrwvkufHt3.jpg",
    id: 84958,
    name: "Loki",
    original_language: "en",
    original_name: "Loki",
    overview:
      "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    poster_path: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 87.5,
    first_air_date: "2021-06-09",
    vote_average: 8.164,
    vote_count: 9887,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r1tMESor8QuPVKP2VxcVEX6t6ad.jpg",
    id: 43348,
    name: "Pablo Escobar: The Drug Lord",
    original_language: "es",
    original_name: "Pablo Escobar: El Patrón del Mal",
    overview:
      "Pablo is a man with a natural ability for business. Early in his life, Pablo is introduced to the business of cocaine and the power it yields. A young life of crime lands Pablo in and out of jail as he builds is criminal empire. Pablo expands his power through politics but it is not long before his conflicts as a Congressman and a drug lord collide. Pablo has his enemies executed, but not before the United States activates its own war on the Medellin cartel.",
    poster_path: "/jZqm7HFuxfH9P0LFjQZ8nzrCUHP.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 327.952,
    first_air_date: "2012-05-28",
    vote_average: 7.588,
    vote_count: 3240,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    id: 82856,
    name: "The Mandalorian",
    original_language: "en",
    original_name: "The Mandalorian",
    overview:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 243.528,
    first_air_date: "2019-11-12",
    vote_average: 8.473,
    vote_count: 9068,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jgb9xICHFX8wTGQ75js4uNbttQs.jpg",
    id: 62688,
    name: "Supergirl",
    original_language: "en",
    original_name: "Supergirl",
    overview:
      "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    poster_path: "/zsaiq8ZclPuneuN7loLEbsh1ANJ.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 123.507,
    first_air_date: "2015-10-26",
    vote_average: 7.334,
    vote_count: 3899,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uNyEVSPeAtJgUBehuQJ8WEFwatN.jpg",
    id: 456,
    name: "The Simpsons",
    original_language: "en",
    original_name: "The Simpsons",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    poster_path: "/zI3E2a3WYma5w8emI35mgq5Iurx.jpg",
    media_type: "tv",
    genre_ids: [10751, 16, 35],
    popularity: 326.35,
    first_air_date: "1989-12-17",
    vote_average: 7.996,
    vote_count: 8874,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    id: 1668,
    name: "Friends",
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    poster_path: "/bRJOwllemPbE4JTQ0TtcVu9efff.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 168.641,
    first_air_date: "1994-09-22",
    vote_average: 8.449,
    vote_count: 6907,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    id: 71446,
    name: "Money Heist",
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 72.993,
    first_air_date: "2017-05-02",
    vote_average: 8.262,
    vote_count: 17560,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/nWfpVLgioDXQsAbfL6UJxYz6d3d.jpg",
    id: 16997,
    name: "The Pacific",
    original_language: "en",
    original_name: "The Pacific",
    overview:
      "Track the intertwined real-life stories of three U.S. Marines – Robert Leckie, John Basilone, and Eugene Sledge – across the vast canvas of the Pacific Theater during World War II. A companion piece to the 2001 miniseries Band of Brothers.",
    poster_path: "/x9Y1IMFdY8Ma222KcQadFEau0EB.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10768],
    popularity: 26.719,
    first_air_date: "2010-03-14",
    vote_average: 7.731,
    vote_count: 2073,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/iux1vKPT7Vw1AzetZb4Jz6wfYsm.jpg",
    id: 92749,
    name: "Moon Knight",
    original_language: "en",
    original_name: "Moon Knight",
    overview:
      "When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.",
    poster_path: "/vKDUmKO6F9bSKKyHhg7YGbgcEeF.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 9648],
    popularity: 78.523,
    first_air_date: "2022-03-30",
    vote_average: 7.852,
    vote_count: 2190,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg",
    id: 87739,
    name: "The Queen's Gambit",
    original_language: "en",
    original_name: "The Queen's Gambit",
    overview:
      "In a Kentucky orphanage in the 1950s, a young girl discovers an astonishing talent for chess while struggling with addiction.",
    poster_path: "/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 47.043,
    first_air_date: "2020-10-23",
    vote_average: 8.541,
    vote_count: 3573,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mRwV4W2BAEpte7xlawJP4fsBpmS.jpg",
    id: 13916,
    name: "Death Note",
    original_language: "ja",
    original_name: "DEATH NOTE",
    overview:
      "Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?",
    poster_path: "/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 10765],
    popularity: 67.652,
    first_air_date: "2006-10-04",
    vote_average: 8.642,
    vote_count: 3417,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    id: 94605,
    name: "Arcane",
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    media_type: "tv",
    genre_ids: [16, 10765, 10759, 18],
    popularity: 44.556,
    first_air_date: "2021-11-06",
    vote_average: 8.755,
    vote_count: 3081,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/thLAoL6VeZGmCyDpCOeoxLvA8yS.jpg",
    id: 76479,
    name: "The Boys",
    original_language: "en",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    poster_path: "/ut4PhX7OP2l2oJhrIUYWnt9pnQU.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759],
    popularity: 151.661,
    first_air_date: "2019-07-25",
    vote_average: 8.472,
    vote_count: 8346,
    origin_country: ["US"],
  },
];
